// 기존 toefl-beginner 데이터를 Supabase로 마이그레이션
// 실행: node migrate.js

const fs = require('fs');
const envFile = fs.readFileSync(__dirname + '/.env', 'utf8');
envFile.split('\n').forEach(line => {
  const [k, ...v] = line.split('=');
  if (k && v.length) process.env[k.trim()] = v.join('=').trim();
});

const SUBJECT_ID = process.env.SUBJECT_ID;
const API = process.env.SUPABASE_MANAGEMENT_API;
const TOKEN = process.env.SUPABASE_MANAGEMENT_TOKEN;
if (!API || !TOKEN || !SUBJECT_ID) { console.error('.env 파일에 SUPABASE_MANAGEMENT_API, SUPABASE_MANAGEMENT_TOKEN, SUBJECT_ID를 설정하세요.'); process.exit(1); }

async function query(sql) {
  const res = await fetch(API, {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${TOKEN}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: sql })
  });
  return res.json();
}

function esc(s) { return (s||'').replace(/'/g, "''"); }
function jsonEsc(obj) { return esc(JSON.stringify(obj)); }

const DAYS = [
  {
    day: 1, lesson: 'Lesson 1-5', title: '현재와 현재진행형',
    grammar: [
      ['He ___ breakfast every morning.', ['eat','eats','is eating','ate'], 1, '3인칭 단수(He) + 습관 → eats'],
      ['Look! The children ___ in the park.', ['play','plays','are playing','played'], 2, 'Look! / right now 같은 표현 → 현재진행형'],
      ['She usually ___ to work by bus.', ['go','goes','is going','went'], 1, 'usually + 3인칭 단수 → goes'],
      ['I ___ TV right now.', ['watch','watches','am watching','watched'], 2, 'right now → 현재진행형 am watching'],
      ['Water ___ at 100 degrees Celsius.', ['boil','boils','is boiling','boiled'], 1, '과학적 사실/불변의 진리 → 현재단순형 boils'],
      ['He ___ a shower at the moment.', ['takes','take','is taking','took'], 2, 'at the moment = 지금 이 순간 → is taking'],
      ['My sister ___ three languages.', ['speak','speaks','is speaking','spoken'], 1, '능력/사실 → speaks'],
      ['They ___ a meeting right now.', ['have','has','are having','had'], 2, 'right now → are having'],
      ['The sun ___ in the east.', ['rise','rises','is rising','rose'], 1, '불변의 사실 → rises'],
      ['I ___ Tom is honest.', ['think','am thinking','thinks','thought'], 0, 'think(생각하다)는 상태동사 → 진행형 불가, think']
    ],
    vocab: [
      ['breakfast', '아침 식사', 'He has breakfast every morning.'],
      ['usually', '보통, 대개', 'She usually walks to work.'],
      ['right now', '지금 바로', 'I am watching TV right now.'],
      ['boil', '끓다', 'Water boils at 100 degrees.'],
      ['at the moment', '지금 이 순간', 'He is taking a shower at the moment.'],
      ['language', '언어', 'She speaks three languages.'],
      ['honest', '정직한', 'I think Tom is honest.'],
      ['rise', '뜨다, 오르다', 'The sun rises in the east.'],
      ['shower', '샤워', 'He takes a shower every day.'],
      ['meeting', '회의', 'They are having a meeting right now.'],
    ],
    writing: [
      ['나는 매일 커피를 마신다.', 'I ___ coffee every day.', ['drink']],
      ['그녀는 지금 전화 통화 중이다.', 'She ___ on the phone now.', ['is talking']],
      ['우리는 런던에 산다.', 'We ___ in London.', ['live']],
      ['그들은 지금 저녁을 먹고 있다.', 'They ___ dinner right now.', ['are eating','are having']],
      ['나의 아버지는 은행에서 일하신다.', 'My father ___ in a bank.', ['works']],
      ['아이들이 지금 밖에서 놀고 있다.', 'The children ___ outside now.', ['are playing']],
      ['고양이는 생선을 좋아한다.', 'Cats ___ fish.', ['like']],
      ['나는 지금 이 문제를 이해하려고 노력하고 있다.', 'I ___ to understand this problem now.', ['am trying']],
      ['그는 매주 일요일에 교회에 간다.', 'He ___ to church every Sunday.', ['goes']],
      ['태양은 동쪽에서 뜬다.', 'The sun ___ in the east.', ['rises']]
    ]
  },
  {
    day: 2, lesson: 'Lesson 6-9', title: '과거와 과거진행형',
    grammar: [
      ['She ___ in Paris for two years.', ['live','lived','was living','lives'], 1, '완성된 과거의 사실 → 과거단순 lived'],
      ['When I arrived, they ___ dinner.', ['had','have','were having','are having'], 2, '내가 도착했을 때 이미 진행 중 → were having'],
      ['He ___ the window yesterday.', ['break','broke','was breaking','broken'], 1, '어제 일어난 완성된 동작 → broke'],
      ['While I ___, someone knocked on the door.', ['slept','sleep','was sleeping','had slept'], 2, '노크가 일어났을 때 자고 있는 중 → was sleeping'],
      ['She ___ to school by bus yesterday.', ['go','goes','went','was going'], 2, '어제 일어난 동작 → went'],
      ['What ___ you do last night?', ['do','did','were','was'], 1, '일반동사 과거 의문문 → did'],
      ['They ___ when I called.', ['study','studied','were studying','are studying'], 2, '내가 전화했을 때 공부하는 중 → were studying'],
      ['I ___ an email to him last Monday.', ['send','sent','was sending','sends'], 1, '지난 월요일 → 과거단순 sent'],
      ['He ___ the phone when his boss walked in.', ['used','uses','was using','use'], 2, '상사가 들어왔을 때 사용 중 → was using'],
      ['We ___ a great time at the party last night.', ['have','had','were having','has'], 1, '어젯밤 파티 → 과거단순 had']
    ],
    vocab: [
      ['arrive', '도착하다', 'When I arrived, they were having dinner.'],
      ['knock', '노크하다', 'Someone knocked on the door.'],
      ['break', '깨뜨리다 (broke-broken)', 'He broke the window yesterday.'],
      ['while', '~하는 동안', 'While I was sleeping, someone called.'],
      ['last night', '어젯밤', 'What did you do last night?'],
      ['call', '전화하다', 'They were studying when I called.'],
      ['send', '보내다 (sent-sent)', 'I sent an email last Monday.'],
      ['walk in', '들어오다', 'His boss walked in suddenly.'],
      ['great time', '즐거운 시간', 'We had a great time at the party.'],
      ['visit', '방문하다', 'We visited Jeju Island last year.'],
    ],
    writing: [
      ['그녀는 어제 도서관에 갔다.', 'She ___ to the library yesterday.', ['went']],
      ['내가 집에 도착했을 때, 그는 자고 있었다.', 'When I got home, he ___.', ['was sleeping']],
      ['우리는 작년에 제주도를 방문했다.', 'We ___ Jeju Island last year.', ['visited']],
      ['그들은 내가 전화했을 때 TV를 보고 있었다.', 'They ___ TV when I called.', ['were watching']],
      ['그는 어젯밤 11시까지 공부했다.', 'He ___ until 11 p.m. last night.', ['studied']],
      ['나는 어렸을 때 피아노를 쳤다.', 'I ___ the piano when I was young.', ['played']],
      ['비가 왔을 때 우리는 산책하고 있었다.', 'We ___ when it started to rain.', ['were walking']],
      ['그녀는 지난주에 새 차를 샀다.', 'She ___ a new car last week.', ['bought']],
      ['그들은 어제 무엇을 했나요?', 'What ___ they do yesterday?', ['did']],
      ['아이들은 내가 왔을 때 뛰어놀고 있었다.', 'The children ___ when I arrived.', ['were running','were playing']]
    ]
  },
  {day:3,lesson:'Lesson 10-15',title:'현재완료와 과거완료',grammar:[['She ___ never been to Australia.',['have','has','had','is'],1,'3인칭 단수(She) → has'],['I ___ just finished my homework.',['have','has','had','am'],0,'1인칭 단수(I) → have'],['By the time he arrived, we ___ already left.',['have','has','had','were'],2,'그가 도착하기 전에 이미 → 과거완료 had'],['She ___ lived in London since 2018.',['have','has','had','is'],1,'since 2018 + 3인칭 단수 → has lived'],['They ___ known each other for years.',['have','has','had','are'],0,'for years + 복수 → have known'],['When she arrived, the train ___ already left.',['have','has','had','was'],2,'그녀가 도착했을 때 이미 → 과거완료 had'],['He ___ lost his wallet. He can\'t find it.',['have','has','had','is'],1,'현재에 영향 미치는 과거 경험 → has lost'],['I ___ already seen that movie three times.',['have','has','had','am'],0,'경험 + I → have seen'],['She said she ___ never tried sushi before.',['have','has','had','was'],2,'말한 시점 이전 → 과거완료 had'],['We ___ been waiting for an hour.',['have','has','had','are'],0,'1시간 동안 계속 → have been waiting']],vocab:[['never','한 번도 ~않다','She has never been to Australia.'],['just','방금, 막','I have just finished my homework.'],['already','이미, 벌써','We had already left.'],['since','~이후로','She has lived here since 2018.'],['for years','수년 동안','They have known each other for years.'],['lose','잃다 (lost-lost)','He has lost his wallet.'],['experience','경험','I have seen that movie three times.'],['try','시도하다, 먹어보다','She had never tried sushi before.'],['wait','기다리다','We have been waiting for an hour.'],['finish','끝내다, 마치다','I have just finished my homework.']],writing:[['나는 그를 세 번 만난 적이 있다.','I ___ met him three times.',['have']],['그녀는 파리에 가 본 적이 없다.','She ___ never been to Paris.',['has']],['그는 방금 점심을 먹었다.','He ___ just had lunch.',['has']],['기차가 도착했을 때 우리는 이미 떠나 있었다.','We ___ already left when the train arrived.',['had']],['나는 2020년부터 영어를 공부하고 있다.','I ___ studied English since 2020.',['have']],['그들은 이미 숙제를 끝냈다.','They ___ already finished their homework.',['have']],['그녀는 그 소식을 들었을 때 울었다.','She cried because she ___ heard the news.',['had']],['우리는 여기 산 지 5년이 되었다.','We ___ lived here for five years.',['have']],['나는 이전에 그 책을 읽어 본 적이 없다.','I ___ never read that book before.',['have']],['그가 집에 도착했을 때, 그녀는 이미 떠나 있었다.','When he arrived home, she ___ already left.',['had']]]},
  {day:4,lesson:'Lesson 16-21',title:'미래·미래진행·미래완료',grammar:[['I ___ call you tomorrow. (즉흥적 결정)',['will','am going to','would','shall'],0,'즉흥적 결정·약속 → will'],['Look at the clouds. It ___ rain.',['will','is going to','rains','rained'],1,'현재 근거 있는 미래 예측 → is going to'],['This time next week, I ___ on the beach.',['will lie','will be lying','lie','am lying'],1,'미래 특정 시점에 진행 중 → will be lying'],['By 2030, she ___ from university.',['will graduate','will have graduated','has graduated','had graduated'],1,'미래 특정 시점까지 완료 → will have graduated'],['She ___ marry Tom. They just got engaged.',['will','is going to','would','shall'],1,'이미 계획된 미래 → is going to'],['Don\'t worry. I ___ help you. (지금 결정)',['am going to','will','would','shall'],1,'그 자리에서 즉흥 결정 → will'],['This time tomorrow, he ___ to Seoul.',['will drive','will be driving','drives','drove'],1,'내일 이 시간에 진행 중 → will be driving'],['By the time you arrive, I ___ cooking.',['will finish','will have finished','have finished','had finished'],1,'네가 도착할 때까지 완료 → will have finished'],['We ___ a picnic this Sunday. (이미 계획됨)',['will have','are going to have','would have','shall have'],1,'이미 계획된 행사 → are going to have'],['Those boxes look heavy. I ___ carry them for you.',['am going to','will','would','shall'],1,'그 자리에서 즉흥 결정 → will']],vocab:[['decision','결정','I will call you tomorrow.'],['predict','예측하다','It is going to rain.'],['graduate','졸업하다','She will have graduated by 2030.'],['engage','약혼하다','They just got engaged.'],['picnic','소풍','We are going to have a picnic.'],['carry','나르다, 옮기다','I will carry them for you.'],['plan','계획, 계획하다','She is going to graduate next year.'],['fly','날다, 비행기를 타다','I will be flying on a plane.'],['novel','소설','He will have finished the novel.'],['careful','조심하는','Be careful! A car is coming!']],writing:[['나는 내일 친구를 만날 것이다.','I ___ meet my friend tomorrow.',['will']],['봐봐! 그가 떨어지려고 해!','Look! He ___ fall!',['is going to']],['그녀는 내년에 대학을 졸업할 계획이다.','She ___ graduate next year.',['is going to']],['내일 이 시간에 나는 비행기를 타고 있을 것이다.','This time tomorrow, I ___ on a plane.',['will be flying','will be sitting']],['그는 2025년까지 그 소설을 다 쓸 것이다.','He ___ the novel by 2025.',['will have finished','will have written']],['걱정 마! 내가 문을 닫을게.','Don\'t worry! I ___ close the door.',['will']],['그들은 이번 여름에 유럽을 여행할 예정이다.','They ___ travel to Europe this summer.',['are going to']],['나는 다음 주 월요일에 새 프로젝트를 시작할 것이다.','I ___ start a new project next Monday.',['will']],['내가 집에 도착할 때쯤, 그녀는 이미 저녁을 만들어 놓을 것이다.','By the time I get home, she ___ cooked dinner.',['will have']],['조심해! 차가 오고 있어!','Be careful! A car ___!',['is coming']]]},
  {day:5,lesson:'Lesson 22-28',title:'조동사 (1)',grammar:[['You ___ see a doctor. You look ill.',['can','should','might','will'],1,'충고/권고 → should'],['She ___ speak four languages.',['can','should','must','would'],0,'능력 → can'],['You ___ smoke here. It\'s forbidden.',['shouldn\'t','can\'t','mustn\'t','might not'],2,'금지 → mustn\'t (강한 금지)'],['He ___ be at home. His lights are on.',['must','can','should','would'],0,'현재 상황의 논리적 추론 → must'],['May I ___ your pen?',['use','to use','using','used'],0,'May I + 동사원형 → use'],['She ___ be tired. She worked all night.',['can','must','should','will'],1,'밤새 일했으니 틀림없이 → must'],['___ you help me with this?',['May','Could','Must','Should'],1,'정중한 부탁 → Could'],['You ___ to be on time for the exam.',['must','should','need','have'],3,'have to = ~해야 한다 (의무)'],['It ___ rain later. Bring an umbrella.',['will','might','must','can'],1,'불확실한 미래 → might'],['She ___ swim when she was five.',['can','could','may','should'],1,'과거의 능력 → could']],vocab:[['forbidden','금지된','You mustn\'t smoke here. It\'s forbidden.'],['permission','허가','May I use your pen?'],['ability','능력','She can speak four languages.'],['advice','충고, 조언','You should see a doctor.'],['necessary','필요한','You have to be on time.'],['polite','예의 바른, 정중한','Could you help me with this?'],['certain','확실한','He must be at home.'],['umbrella','우산','It might rain. Bring an umbrella.'],['regularly','규칙적으로','You should exercise regularly.'],['possible','가능한','That can\'t be true.']],writing:[['너는 규칙적으로 운동해야 한다.','You ___ exercise regularly.',['should']],['그는 수영을 할 줄 안다.','He ___ swim.',['can']],['여기서 담배를 피워서는 안 된다.','You ___ smoke here.',['must not','mustn\'t','cannot','can\'t']],['그녀는 피곤함에 틀림없다.','She ___ be tired.',['must']],['내일 비가 올지도 모른다.','It ___ rain tomorrow.',['might','may']],['제가 창문을 열어도 될까요?','___ I open the window?',['May','Can','Could']],['그는 5살 때 자전거를 탈 수 있었다.','He ___ ride a bike when he was 5.',['could']],['너는 지금 당장 그것을 할 필요가 없다.','You ___ do it right now.',['don\'t have to','don\'t need to']],['그들은 8시까지 도착해야 한다.','They ___ arrive by 8 o\'clock.',['must','have to','should']],['그것은 사실일 리가 없다.','That ___ be true.',['can\'t','cannot']]]},
  {day:6,lesson:'Lesson 22-28',title:'조동사 (2)',grammar:[['She would rather ___ home.',['stay','to stay','staying','stayed'],0,'would rather + 동사원형 → stay'],['He used to ___ near here.',['live','to live','living','lived'],0,'used to + 동사원형 → live'],['You had better ___ a coat. It\'s cold.',['wear','to wear','wearing','wore'],0,'had better + 동사원형 → wear'],['I would rather ___ tea than coffee.',['drink','to drink','drinking','drank'],0,'would rather + 동사원형 → drink'],['She ___ rather not come to the party.',['will','would','should','might'],1,'would rather not + 동사원형'],['He used to ___ a lot when he was young.',['smoke','to smoke','smoking','smoked'],0,'used to + 동사원형 → smoke'],['You had better ___ late again.',['not be','not to be','being','be not'],0,'had better not + 동사원형'],['Would you rather ___ or stay home?',['go out','to go out','going out','went out'],0,'would rather + 동사원형'],['They used to ___ here before the park was built.',['play','to play','playing','played'],0,'used to + 동사원형 → play'],['I\'d rather you ___ quiet.',['keep','kept','to keep','keeping'],1,'would rather + 주어 + 과거동사 → kept']],vocab:[['rather','차라리, 오히려','I would rather stay home.'],['used to','예전에 ~하곤 했다','He used to live near here.'],['had better','~하는 게 좋겠다','You had better wear a coat.'],['prefer','선호하다','I would rather drink tea than coffee.'],['quit','그만두다','She used to smoke but she quit.'],['coat','코트, 외투','It\'s cold. Wear a coat.'],['hurry','서두르다','You had better hurry.'],['jog','조깅하다','She used to jog every day.'],['alone','혼자','I would rather walk alone.'],['quiet','조용한','I\'d rather you kept quiet.']],writing:[['나는 커피보다 차를 더 좋아한다.','I would rather ___ tea than coffee.',['drink']],['그는 예전에 담배를 피웠다.','He used to ___.',['smoke']],['너는 빨리 의사에게 가는 게 좋겠어.','You had better ___ a doctor soon.',['see']],['나는 여기 있을래.','I\'d rather ___ here.',['stay']],['그녀는 예전에 매일 조깅을 했다.','She used to ___ every day.',['jog','run']],['너는 서두르는 게 좋을 거야.','You had better ___.',['hurry']],['나는 차라리 혼자 걸어가겠어.','I would rather ___ alone.',['walk','go']],['그들은 예전에 이 집에서 살았다.','They used to ___ in this house.',['live']],['너는 오늘 밤 일찍 자는 게 좋겠어.','You had better ___ to bed early tonight.',['go']],['그는 차라리 집에 있겠다고 했다.','He said he would rather ___ home.',['stay']]]},
  {day:7,lesson:'Lesson 29-32',title:'의문문',grammar:[['___ you speak English?',['Are','Do','Does','Is'],1,'일반동사(speak) 의문문 → Do'],['___ she working right now?',['Do','Does','Is','Are'],2,'진행형 의문문 → Is'],['Where ___ he live?',['do','does','is','are'],1,'3인칭 단수 → does'],['How long ___ you been here?',['do','does','have','are'],2,'현재완료 의문문 → have'],['___ did she say?',['Who','What','Which','Whose'],1,'말한 내용 → What'],['Who ___ the door? (누가 열었나)',['open','opens','opened','opening'],2,'의문사가 주어일 때 → 과거 opened'],['___ is this book? (누구의)',['Who','Whose','Whom','Which'],1,'소유 의문사 → Whose'],['___ did you go last weekend?',['Where','When','Why','How'],0,'장소 → Where'],['She likes coffee, ___ she?',['does','doesn\'t','is','isn\'t'],1,'앞이 긍정 → 뒤는 부정 doesn\'t'],['They are from Korea, ___ they?',['are','aren\'t','do','don\'t'],1,'are → 부가의문문 aren\'t']],vocab:[['question','질문','Can I ask you a question?'],['whose','누구의','Whose book is this?'],['whether','~인지 아닌지','I don\'t know whether he\'s coming.'],['tag question','부가의문문','She likes coffee, doesn\'t she?'],['reply','대답하다','She didn\'t reply to my question.'],['realize','깨닫다','Did you realize the mistake?'],['wonder','궁금해하다','I wonder where she lives.'],['negative','부정의','They aren\'t from Korea, are they?'],['curious','궁금한','I am curious about his answer.'],['pronounce','발음하다','How do you pronounce this word?']],writing:[['그녀는 어디에 사나요?','___ does she live?',['Where']],['그들은 지금 무엇을 하고 있나요?','___ are they doing now?',['What']],['당신은 얼마나 오래 영어를 공부했나요?','___ have you studied English?',['How long']],['이 가방은 누구 것인가요?','___ bag is this?',['Whose']],['왜 그녀는 울고 있나요?','___ is she crying?',['Why']],['그들은 한국에서 왔죠, 그렇지 않나요?','They are from Korea, ___ they?',['aren\'t']],['이 중에서 어떤 것을 원하세요?','___ one do you want?',['Which']],['그는 보통 몇 시에 일어나나요?','___ does he usually get up?',['What time']],['그녀가 그 문을 열었나요?','___ she open the door?',['Did']],['당신은 차를 운전할 줄 아시죠?','You can drive, ___ you?',['can\'t']]]},
  {day:8,lesson:'Lesson 33-35',title:'수동태',grammar:[['The cake ___ by Mary.',['baked','was baked','is baking','bakes'],1,'과거 수동태: be동사 과거 + p.p.'],['This book ___ in 1990.',['wrote','was written','writes','is written'],1,'1990년에 쓰여진 → was written'],['The window ___ by the children.',['broke','was broken','is breaking','breaks'],1,'아이들에 의해 깨진 → was broken'],['English ___ all over the world.',['speaks','spoke','is spoken','was speaking'],2,'현재 사실 수동태 → is spoken'],['The email ___ tomorrow.',['sends','will be sent','is sending','sent'],1,'내일 보내질 것 → will be sent'],['The meeting ___ right now.',['is being held','holds','held','is holding'],0,'지금 진행 중 수동태 → is being held'],['She ___ promoted last month.',['was','is','were','has'],0,'지난달 → 과거 수동태 was promoted'],['The new school ___ by next year.',['will build','will be built','builds','is building'],1,'미래 수동태 → will be built'],['I ___ told to wait.',['am','was','were','been'],1,'과거 수동태 → was told'],['The letter ___ already been written.',['is','was','has','have'],2,'현재완료 수동태 → has been written']],vocab:[['passive','수동의','The cake was baked by Mary.'],['promote','승진시키다','She was promoted last month.'],['announce','발표하다','The news will be announced tomorrow.'],['hold','개최하다 (held-held)','The meeting is being held now.'],['active','능동의','Mary baked the cake.'],['translate','번역하다','This book was translated into Korean.'],['discover','발견하다','America was discovered in 1492.'],['invent','발명하다','The telephone was invented by Bell.'],['deliver','배달하다','The package will be delivered tomorrow.'],['repair','수리하다','The car is being repaired now.']],writing:[['그 케이크는 내 어머니가 만드셨다.','The cake ___ by my mother.',['was made']],['이 소설은 2010년에 쓰여졌다.','This novel ___ in 2010.',['was written']],['영어는 전 세계에서 사용된다.','English ___ all over the world.',['is spoken','is used']],['그 건물은 내년에 지어질 것이다.','The building ___ next year.',['will be built']],['그 창문은 누군가에 의해 깨졌다.','The window ___ by someone.',['was broken']],['그녀는 작년에 승진되었다.','She ___ last year.',['was promoted']],['그 편지는 이미 보내졌다.','The letter ___ already been sent.',['has']],['회의는 지금 진행되고 있다.','The meeting ___ right now.',['is being held']],['그 소식은 내일 발표될 것이다.','The news ___ tomorrow.',['will be announced']],['이 노래는 많은 사람들에게 알려져 있다.','This song ___ known to many people.',['is']]]},
  {day:9,lesson:'Lesson 36-46',title:'ing와 to부정사 (1)',grammar:[['She enjoys ___ books.',['read','reads','reading','to read'],2,'enjoy + -ing → reading'],['I want ___ a pizza.',['eat','eating','to eat','ate'],2,'want + to부정사 → to eat'],['He stopped ___ (담배 피우는 것을 그만뒀다)',['smoke','to smoke','smoking','smoked'],2,'stop + -ing = ~하는 것을 멈추다'],['She decided ___ a new job.',['find','finding','to find','found'],2,'decide + to부정사 → to find'],['They finished ___ the project.',['complete','completing','to complete','completed'],1,'finish + -ing → completing'],['I\'m looking forward to ___ you.',['meet','meets','meeting','met'],2,'look forward to + -ing (to = 전치사)'],['He promised ___ on time.',['be','being','to be','been'],2,'promise + to부정사 → to be'],['Avoid ___ fast food every day.',['eat','eating','to eat','ate'],1,'avoid + -ing → eating'],['She agreed ___ us.',['help','helping','to help','helped'],2,'agree + to부정사 → to help'],['I can\'t help ___ when I see him.',['laugh','to laugh','laughing','laughed'],2,'can\'t help + -ing = ~을 참을 수 없다']],vocab:[['enjoy','즐기다 (+ing)','She enjoys reading books.'],['decide','결심하다 (+to)','She decided to find a new job.'],['avoid','피하다 (+ing)','Avoid eating fast food every day.'],['promise','약속하다 (+to)','He promised to be on time.'],['agree','동의하다 (+to)','She agreed to help us.'],['complete','완성하다','They finished completing the project.'],['forward','앞으로','I look forward to meeting you.'],['refuse','거절하다 (+to)','He refused to answer the question.'],['suggest','제안하다 (+ing)','She suggested going to a movie.'],['practice','연습하다 (+ing)','I practice speaking English.']],writing:[['그는 피아노 치는 것을 즐긴다.','He enjoys ___ the piano.',['playing']],['나는 영어를 배우기를 원한다.','I want ___ English.',['to learn']],['그녀는 숙제하는 것을 끝냈다.','She finished ___ her homework.',['doing']],['그는 제시간에 오겠다고 약속했다.','He promised ___ on time.',['to come','to be']],['나는 네 목소리를 듣기를 기대한다.','I look forward to ___ your voice.',['hearing']],['그들은 파리로 여행하기로 결심했다.','They decided ___ to Paris.',['to travel','to go']],['나는 그녀에게 거짓말하는 것을 피한다.','I avoid ___ to her.',['lying']],['그는 웃음을 참을 수가 없었다.','He couldn\'t help ___ .',['laughing']],['그녀는 우리를 돕겠다고 동의했다.','She agreed ___ us.',['to help']],['나는 거기서 기다리는 것을 그만뒀다.','I stopped ___ there.',['waiting']]]},
  {day:10,lesson:'Lesson 36-46',title:'ing와 to부정사 (2)',grammar:[['He remembered ___ the door. (문 잠근 것을 기억했다)',['lock','locking','to lock','locked'],1,'remember + -ing = 이미 한 것을 기억하다'],['She forgot ___ her keys. (열쇠를 못 챙겼다)',['bring','brought','to bring','bringing'],2,'forget + to부정사 = 해야 할 것을 잊다'],['I tried ___ the lock. (열려고 시도했다)',['open','opens','opening','to open'],3,'try + to부정사 = ~하려고 시도하다'],['He went on ___ after the break. (계속 말했다)',['speak','spoke','speaking','to speak'],2,'go on + -ing = 계속 ~하다'],['I regret ___ you that you failed. (알려드려서 유감)',['tell','told','telling','to tell'],3,'regret + to부정사 = ~하게 되어 유감이다'],['She tried ___ the cake. (시험 삼아 먹어봤다)',['eating','to eat','eat','ate'],0,'try + -ing = 시험 삼아 해보다'],['Don\'t forget ___ me tomorrow. (내일 전화해야 함)',['call','calling','to call','called'],2,'forget + to부정사 = 해야 할 것을 잊다'],['He stopped ___ his friend. (인사하려고 멈췄다)',['greet','greeting','to greet','greeted'],2,'stop + to부정사 = ~하기 위해 멈추다'],['I remember ___ her at the party. (만났던 것 기억)',['meet','met','meeting','to meet'],2,'remember + -ing = 이미 한 것을 기억하다'],['She regrets ___ that. (그렇게 말한 것을 후회)',['say','saying','to say','said'],1,'regret + -ing = 이미 한 것을 후회하다']],vocab:[['remember','기억하다 (+ing 과거/+to 미래)','I remember locking the door.'],['forget','잊다 (+to 해야할 것)','She forgot to bring her keys.'],['regret','후회하다 (+ing 과거/+to 유감)','She regrets saying those words.'],['go on','계속하다 (+ing)','He went on speaking after the break.'],['lock','잠그다','Did you lock the door?'],['attempt','시도하다','He tried to open the lock.'],['greet','인사하다','He stopped to greet his friend.'],['wallet','지갑','He stopped to find his wallet.'],['break','휴식; 깨뜨리다','He spoke after the break.'],['truth','진실','Despite knowing the truth, she kept quiet.']],writing:[['나는 문을 잠갔던 것을 기억한다.','I remember ___ the door.',['locking']],['그녀는 열쇠를 가져오는 것을 잊었다.','She forgot ___ her keys.',['to bring']],['나는 그 음식을 시험 삼아 먹어봤다.','I tried ___ the food.',['eating']],['그는 계속해서 노래를 불렀다.','He went on ___.',['singing']],['전화하는 것을 잊지 마!','Don\'t forget ___ me!',['to call']],['그녀는 창문을 열어보려고 했다.','She tried ___ the window.',['to open']],['나는 그 사실을 말해서 유감이다.','I regret ___ that.',['saying']],['그는 지갑을 찾으려고 걸음을 멈췄다.','He stopped ___ his wallet.',['to find','to look for']],['나는 어렸을 때 거기 살았던 것을 기억한다.','I remember ___ there when I was young.',['living']],['그녀는 그 말을 한 것을 후회한다.','She regrets ___ those words.',['saying']]]},
  {day:11,lesson:'Lesson 47-50',title:'명사',grammar:[['I need some ___.',['advice','advices','an advice','the advices'],0,'advice는 불가산명사 → 복수형 없음'],['There is a lot of ___ today.',['traffic','traffics','a traffic','the traffics'],0,'traffic은 불가산명사'],['She has two ___.',['child','childs','children','childrens'],2,'child의 불규칙 복수형 → children'],['He gave me some ___.',['informations','information','an information','the information'],1,'information은 불가산명사'],['The ___ are on the table.',['knife','knifes','knives','knive'],2,'knife의 복수형: knife → knives'],['I drink three ___ of water a day.',['glass','glasses','a glass','glassing'],1,'불가산명사 단위 → three glasses of water'],['She has long ___.',['hair','hairs','a hair','the hairs'],0,'hair는 불가산명사 (집합적)'],['There were many ___ at the concert.',['peoples','person','people','a people'],2,'people = 사람들 (복수 의미)'],['I have a lot of ___.',['homeworks','homework','a homework','the homeworks'],1,'homework는 불가산명사'],['The ___ is running fast.',['deer','deers','deeres','a deers'],0,'deer는 단수·복수 동형']],vocab:[['advice','조언 (불가산)','I need some advice.'],['traffic','교통 (불가산)','There is a lot of traffic today.'],['information','정보 (불가산)','He gave me some information.'],['homework','숙제 (불가산)','I have a lot of homework.'],['furniture','가구 (불가산)','We bought new furniture.'],['luggage','짐, 수하물 (불가산)','How much luggage do you have?'],['knife','칼 (복수: knives)','The knives are on the table.'],['child','아이 (복수: children)','She has two children.'],['deer','사슴 (단복수 동형)','The deer is running fast.'],['person','사람 (복수: people)','Many people came to the concert.']],writing:[['그녀는 조언이 필요하다.','She needs some ___.',['advice']],['칼들이 서랍 안에 있다.','The ___ are in the drawer.',['knives']],['나는 오늘 할 일이 많다.','I have a lot of ___ today.',['work']],['그 아이들은 공원에서 놀고 있다.','The ___ are playing in the park.',['children']],['교통 체증이 심하다.','There is a lot of ___ on the road.',['traffic']],['그는 정보가 필요하다.','He needs some ___.',['information']],['물 세 잔을 마셔라.','Drink three ___ of water.',['glasses']],['여자가 저기 서있다.','A ___ is standing over there.',['woman']],['많은 사람들이 그 콘서트에 왔다.','Many ___ came to the concert.',['people']],['나는 숙제가 많다.','I have a lot of ___.',['homework']]]},
  {day:12,lesson:'Lesson 51-54',title:'관사',grammar:[['She is ___ nurse.',['a','an','the','(없음)'],1,'모음(n) 앞 → an'],['I saw ___ movie. ___ movie was great.',['a / The','the / The','an / A','a / A'],0,'처음 언급 a, 다시 언급 The'],['He plays ___ guitar.',['a','an','the','(없음)'],2,'악기 앞 → the'],['___ sun rises in the east.',['A','An','The','(없음)'],2,'유일한 것 → The'],['I had ___ apple for breakfast.',['a','an','the','(없음)'],1,'모음(a) 앞 → an'],['She lives on ___ Main Street.',['a','an','the','(없음)'],3,'거리명 앞 → 관사 없음'],['I go to ___ school by bus.',['a','an','the','(없음)'],3,'목적으로 가는 경우 → 관사 없음'],['He is ___ honest man.',['a','an','the','(없음)'],1,'honest는 모음 발음(h묵음) → an'],['We visited ___ Eiffel Tower.',['a','an','the','(없음)'],2,'유일한 건물 → The'],['She can play ___ piano well.',['a','an','the','(없음)'],2,'악기 앞 → the']],vocab:[['article','관사','Use the correct article before the noun.'],['definite','한정된, 특정한','Use "the" for definite nouns.'],['indefinite','불특정한','"A" and "an" are indefinite articles.'],['instrument','악기; 도구','He plays the guitar.'],['unique','유일한','The sun is unique.'],['vowel','모음','Use "an" before vowel sounds.'],['consonant','자음','Use "a" before consonant sounds.'],['honest','정직한 (h 묵음)','He is an honest man.'],['university','대학 (u가 자음 발음)','She goes to a university.'],['specific','특정한, 구체적인','Use "the" for specific things.']],writing:[['그녀는 의사다.','She is ___ doctor.',['a']],['나는 어젯밤 영화를 봤다. 그 영화는 훌륭했다.','I watched ___ movie last night. ___ movie was great.',['a / The','a/The']],['그는 기타를 친다.','He plays ___ guitar.',['the']],['태양은 동쪽에서 뜬다.','___ sun rises in the east.',['The']],['그녀는 정직한 사람이다.','She is ___ honest person.',['an']],['나는 버스로 학교에 간다.','I go to ___ school by bus.',['-','(없음)','없음']],['우리는 에펠탑을 방문했다.','We visited ___ Eiffel Tower.',['the','The']],['나는 아침에 사과를 먹었다.','I had ___ apple for breakfast.',['an']],['그는 피아노를 잘 친다.','He plays ___ piano well.',['the']],['그녀는 Main Street에 산다.','She lives on ___ Main Street.',['-','(없음)','없음']]]},
  {day:13,lesson:'Lesson 55-58',title:'대명사와 소유격',grammar:[['___ is my friend.',['Her','She','Hers','Him'],1,'주어 자리 → 주격 She'],['This is ___ book.',['I','my','me','mine'],1,'명사(book) 앞 → 소유격 my'],['This book is ___.',['I','my','me','mine'],3,'명사 없이 독립적 → 소유대명사 mine'],['He hurt ___ during the game.',['him','his','himself','he'],2,'주어=목적어 → 재귀대명사 himself'],['She made the cake ___. (혼자서)',['her','hers','herself','she'],2,'직접 했음 강조 → herself'],['___ did you talk to?',['Who','Whom','Whose','What'],1,'전치사/동사의 목적어 → 목적격 Whom'],['This is the girl ___ helped me.',['who','whom','whose','which'],0,'관계대명사 주격(사람) → who'],['The bag ___ you gave me is beautiful.',['who','whose','which','whom'],2,'관계대명사 사물 → which/that'],['Each student ___ a book.',['have','has','are having','had'],1,'each + 단수명사 → 단수동사 has'],['Nobody ___ what happened.',['know','knows','are knowing','have known'],1,'nobody → 단수동사 knows']],vocab:[['pronoun','대명사','She is a pronoun for a female.'],['possessive','소유격의','My, your, his are possessive adjectives.'],['reflexive','재귀의','He hurt himself during the game.'],['objective','목적격의','Give it to him.'],['subjective','주격의','She is my friend.'],['relative','관계의','This is the girl who helped me.'],['independent','독립적인','This book is mine.'],['emphasize','강조하다','She made the cake herself.'],['each','각각의 (+단수)','Each student has a book.'],['nobody','아무도 ~않다 (+단수)','Nobody knows what happened.']],writing:[['이것은 내 책이다.','This is ___ book.',['my']],['이 책은 내 것이다.','This book is ___.',['mine']],['그녀는 혼자서 그것을 했다.','She did it ___.',['herself']],['저 가방은 그녀의 것이다.','That bag is ___.',['hers']],['그가 나를 도와줬다.','___ helped me.',['He']],['나는 그를 공항에서 봤다.','I saw ___ at the airport.',['him']],['당신이 나에게 준 선물은 아름답다.','The gift ___ you gave me is beautiful.',['that','which']],['나를 도와준 소녀가 저기 있다.','The girl ___ helped me is over there.',['who']],['각 학생은 책을 가지고 있다.','Each student ___ a book.',['has']],['아무도 그것을 모른다.','Nobody ___ that.',['knows']]]},
  {day:14,lesson:'Lesson 59-64',title:'수량 표현',grammar:[['I have ___ friends here. (몇 명 있다)',['few','a few','little','a little'],1,'가산명사 + 있다 → a few'],['She has ___ money. (조금 있다)',['few','a few','little','a little'],3,'불가산명사 + 있다 → a little'],['___ students passed the exam. (대부분)',['Most of','Most','The most','A most'],1,'한정사 없이 → Most students'],['___ of the students passed. (학생들의 대부분)',['Most of','Most','The most','A most'],0,'the students 앞 → Most of the'],['There is ___ water in the glass.',['few','a few','little','a little'],3,'불가산명사 + 있다 → a little'],['He has very ___ friends. He\'s lonely.',['few','a few','little','a little'],0,'가산명사 + 거의 없다 → few'],['I need ___ help.',['few','a few','little','a little'],3,'불가산명사 + 조금 → a little'],['___ student in the class passed. (모든)',['Every','Every of','All','All of'],0,'Every + 단수명사'],['There aren\'t ___ people here.',['some','any','no','much'],1,'부정문 → any'],['She has ___ books than I do.',['much more','many more','more much','more many'],1,'가산명사 비교 → many more']],vocab:[['few','거의 없는 (가산)','He has very few friends.'],['a few','조금 있는 (가산)','I have a few friends here.'],['little','거의 없는 (불가산)','There is little water left.'],['a little','조금 있는 (불가산)','She has a little money.'],['most','대부분의','Most students passed the exam.'],['every','모든 (+단수)','Every student must do homework.'],['quantity','양, 수량','What quantity do you need?'],['plenty','충분한, 많은','We have plenty of time.'],['several','몇몇의','Several people were absent.'],['enough','충분한','Do we have enough food?']],writing:[['나는 친구가 거의 없다.','I have ___ friends.',['few']],['그녀는 돈이 조금 있다.','She has ___ money.',['a little']],['대부분의 학생들이 시험에 합격했다.','___ students passed the exam.',['Most']],['물이 거의 없다.','There is very ___ water.',['little']],['그에게는 친구가 몇 명 있다.','He has ___ friends.',['a few']],['모든 학생은 숙제를 해야 한다.','___ student must do homework.',['Every']],['냉장고에 음식이 없다.','There isn\'t ___ food in the fridge.',['any']],['나는 그 학생들의 대부분을 안다.','I know ___ the students.',['most of','Most of']],['그녀는 나보다 책이 훨씬 더 많다.','She has ___ books than me.',['many more']],['그는 우유를 조금 마셨다.','He drank ___ milk.',['a little']]]},
  {day:15,lesson:'Lesson 65-73',title:'형용사(분사)·부사 (1)',grammar:[['She felt ___ after the long walk.',['tire','tired','tiring','tiredly'],1,'사람이 느끼는 감정/상태 → tired'],['The book was very ___.',['bored','boring','bore','boringly'],1,'사물이 주어 → boring'],['He ran ___.',['quick','quickness','quickly','quicked'],2,'동사 수식 → 부사 quickly'],['She is a ___ student.',['hard-working','hard-worked','hardly-working','work-hard'],0,'복합형용사로 명사 수식 → hard-working'],['I was ___ surprised by the news.',['extreme','extremely','extremeness','extreming'],1,'형용사(surprised) 수식 → 부사 extremely'],['The movie was ___. I fell asleep.',['bored','bore','boring','boringly'],2,'사물(movie)이 주어 → boring'],['She speaks English ___.',['fluent','fluently','fluented','fluenting'],1,'동사 수식 → 부사 fluently'],['He looked ___ when I saw him.',['happily','happy','happiness','happying'],1,'look + 형용사(보어) → happy'],['The children were ___ about the trip.',['excite','exciting','excited','excitedly'],2,'사람이 느끼는 감정 → excited'],['She is ___ tall to reach the shelf.',['enough','too','very','so'],1,'too ... to = 너무 ~해서 ...할 수 없다']],vocab:[['tired','피곤한 (사람 감정)','She felt tired after the walk.'],['tiring','피곤하게 하는 (원인)','The work was very tiring.'],['boring','지루한 (원인)','The movie was boring.'],['bored','지루해하는 (사람)','I was bored during the class.'],['excited','흥분한 (사람)','The children were excited about the trip.'],['exciting','흥분시키는 (원인)','The game was very exciting.'],['fluently','유창하게 (부사)','She speaks English fluently.'],['extremely','극도로 (부사)','I was extremely surprised.'],['embarrassing','당황스러운 (원인)','The situation was embarrassing.'],['disappointed','실망한 (사람)','I was disappointed with the result.']],writing:[['나는 그 소식에 충격을 받았다.','I was ___ by the news.',['shocked']],['그 영화는 매우 지루했다.','The movie was very ___.',['boring']],['그녀는 영어를 유창하게 말한다.','She speaks English ___.',['fluently']],['그는 행복해 보였다.','He looked ___.',['happy']],['아이들은 그 여행에 흥분했다.','The children were ___ about the trip.',['excited']],['그 책은 매우 흥미로웠다.','The book was very ___.',['interesting']],['그는 매우 빠르게 달렸다.','He ran very ___.',['quickly','fast']],['그녀는 완전히 피곤했다.','She was ___ tired.',['completely','extremely','very']],['그 상황은 매우 당황스러웠다.','The situation was very ___.',['embarrassing']],['나는 그 결과에 실망했다.','I was ___ with the result.',['disappointed']]]},
  {day:16,lesson:'Lesson 65-73',title:'형용사(분사)·부사 (2)',grammar:[['The soup smells ___.',['good','well','nicely','greatly'],0,'감각동사(smell) + 형용사 → good'],['She plays piano ___.',['beautiful','beauty','beautifully','beauteous'],2,'동사 수식 → 부사 beautifully'],['I ___ forget where I put my keys. (항상)',['ever','never','always','seldom'],2,'항상 ~ → always'],['He is a ___ known author.',['wide','widely','wider','wideness'],1,'형용사(known) 수식 → 부사 widely'],['She can run ___ than her brother.',['fast','faster','fastest','more fast'],1,'비교급 → faster'],['The music sounds ___.',['loudly','loud','louder','louding'],1,'감각동사(sound) + 형용사 → loud'],['He works ___ than anyone in the office.',['hard','harder','hardest','more hard'],1,'비교급 → harder'],['She is ___ the most talented student.',['by far','by much','by large','by great'],0,'최상급 강조 → by far'],['He ___ exercises. He\'s very healthy.',['rarely','never','always','seldom'],2,'건강하므로 → always (항상 운동)'],['The flowers smell ___ in the garden.',['wonderful','wonderfully','wonder','wondrous'],0,'감각동사(smell) + 형용사 → wonderful']],vocab:[['smell','냄새가 나다 (+형용사)','The soup smells good.'],['sound','~처럼 들리다 (+형용사)','The music sounds loud.'],['beautifully','아름답게 (부사)','She plays piano beautifully.'],['widely','널리 (부사)','He is a widely known author.'],['seldom','거의 ~않는','She seldom arrives late.'],['rarely','드물게, 거의 ~않는','He rarely exercises.'],['always','항상','He always gets up early.'],['by far','단연, 월등히','She is by far the most talented.'],['comparative','비교급의','She can run faster than her brother.'],['wonder','경이, 놀라움','The flowers smell wonderful.']],writing:[['수프가 좋은 냄새가 난다.','The soup smells ___.',['good']],['그녀는 피아노를 아름답게 연주한다.','She plays piano ___.',['beautifully']],['음악이 크게 들린다.','The music sounds ___.',['loud']],['그는 항상 일찍 일어난다.','He ___ gets up early.',['always']],['그녀는 거의 늦지 않는다.','She ___ arrives late.',['rarely','seldom','never']],['그는 사무실에서 누구보다 열심히 일한다.','He works ___ than anyone in the office.',['harder']],['그 꽃들은 정원에서 훌륭한 냄새가 난다.','The flowers smell ___ in the garden.',['wonderful']],['그녀는 단연코 가장 재능 있는 학생이다.','She is ___ the most talented student.',['by far']],['이 책은 널리 알려져 있다.','This book is ___ known.',['widely']],['그는 그의 형보다 더 빠르게 달릴 수 있다.','He can run ___ than his brother.',['faster']]]},
  {day:17,lesson:'Lesson 74-79',title:'비교급과 최상급',grammar:[['She is ___ than her sister.',['tall','taller','tallest','more tall'],1,'두 대상 비교 → 비교급 taller'],['This is ___ movie I\'ve ever seen.',['good','better','the best','the goodest'],2,'ever + 경험 → 최상급 the best'],['He speaks English ___ than me.',['fluent','more fluent','more fluently','fluentlier'],2,'부사 비교급 → more fluently'],['The more you practice, ___ you become.',['good','better','the better','the good'],2,'배례비교 → the + 비교급'],['She is ___ as tall as her mother.',['as','so','than','more'],0,'동등비교 → as ... as'],['This problem is ___ than I thought.',['more difficult','difficulter','most difficult','difficultmost'],0,'2음절 이상 → more difficult'],['He is by far ___ player on the team.',['good','better','the best','most good'],2,'최상급 강조 by far → the best'],['She works ___ as hard ___ he does.',['as, as','so, so','as, so','more, as'],0,'동등비교 → as ... as'],['This is ___ expensive bag in the shop.',['more','the more','the most','most'],2,'최상급 → the most expensive'],['My bag is ___ than yours.',['heavy','heavier','more heavy','heaviest'],1,'1음절 → 비교급 heavier']],vocab:[['comparison','비교','Use comparatives for comparison.'],['superlative','최상급의','This is the best movie ever.'],['equal','동등한','She is as tall as her mother.'],['fluent','유창한','He speaks more fluently than me.'],['practice','연습','The more you practice, the better.'],['difficult','어려운','This is more difficult than I thought.'],['expensive','비싼','This is the most expensive bag.'],['talented','재능 있는','She is the most talented student.'],['inferior','열등한','This product is inferior to that one.'],['superior','우월한','His work is superior to mine.']],writing:[['그녀는 그녀의 여동생보다 키가 크다.','She is ___ than her sister.',['taller']],['이것은 내가 본 것 중 가장 좋은 영화다.','This is ___ movie I\'ve ever seen.',['the best']],['그는 나보다 영어를 더 유창하게 말한다.','He speaks English ___ than me.',['more fluently']],['그녀는 그녀의 어머니만큼 키가 크다.','She is as tall ___ her mother.',['as']],['이 가방은 당신 것보다 더 무겁다.','My bag is ___ than yours.',['heavier']],['연습할수록 더 잘하게 된다.','The more you practice, ___ you get.',['the better']],['그는 팀에서 단연코 최고의 선수다.','He is by far ___ player on the team.',['the best']],['이것은 상점에서 가장 비싼 가방이다.','This is ___ bag in the shop.',['the most expensive']],['그것은 내가 생각했던 것보다 더 어렵다.','It is ___ than I thought.',['more difficult']],['그녀는 그만큼 열심히 일한다.','She works as hard ___ he does.',['as']]]},
  {day:18,lesson:'Lesson 80-90',title:'전치사와 구동사',grammar:[['She arrived ___ the airport.',['in','at','on','to'],1,'특정 장소(공항) → at'],['He has lived ___ Seoul for 10 years.',['at','on','in','to'],2,'도시/나라 → in'],['The exam is ___ Monday.',['in','at','on','by'],2,'요일 → on'],['I wake up ___ 7 o\'clock.',['in','at','on','by'],1,'시간 → at'],['She was born ___ 1995.',['in','at','on','by'],0,'연도/월/계절 → in'],['Can you turn ___ the TV? (켜줘)',['on','off','up','down'],0,'turn on = 켜다'],['Please turn ___ the music. It\'s too loud.',['on','off','up','down'],3,'turn down = (소리를) 줄이다'],['She gave ___ her job and traveled.',['up','on','in','out'],0,'give up = 포기하다'],['I ran ___ Tom at the supermarket.',['across','into','over','up'],1,'run into = 우연히 만나다'],['The game was called ___ due to rain.',['off','up','on','in'],0,'call off = 취소하다']],vocab:[['arrive at','~에 도착하다 (장소)','She arrived at the airport.'],['turn on','켜다','Can you turn on the TV?'],['turn off','끄다','Please turn off the lights.'],['turn down','줄이다 (소리)','Turn down the music.'],['give up','포기하다','She gave up her job.'],['run into','우연히 만나다','I ran into Tom at the store.'],['call off','취소하다','The game was called off.'],['look for','찾다','I am looking for my keys.'],['pick up','줍다; 데리러 가다','Pick me up at the station.'],['put off','미루다, 연기하다','Don\'t put off your homework.']],writing:[['그녀는 공항에 도착했다.','She arrived ___ the airport.',['at']],['그는 서울에 10년 동안 살았다.','He has lived ___ Seoul for 10 years.',['in']],['시험은 월요일이다.','The exam is ___ Monday.',['on']],['나는 7시에 일어난다.','I wake up ___ 7 o\'clock.',['at']],['TV 좀 켜줄래?','Can you turn ___ the TV?',['on']],['음악 좀 줄여줘. 너무 시끄럽다.','Turn ___ the music. It\'s too loud.',['down']],['그녀는 담배를 끊었다.','She gave ___ smoking.',['up']],['나는 슈퍼마켓에서 Tom을 우연히 만났다.','I ran ___ Tom at the supermarket.',['into']],['경기는 비로 인해 취소되었다.','The game was called ___ due to rain.',['off']],['그녀는 1990년에 태어났다.','She was born ___ 1990.',['in']]]},
  {day:19,lesson:'Lesson 91-95',title:'부사절과 분사구문',grammar:[['___ it was raining, we went for a walk.',['Although','Because','So','While'],0,'양보 → Although/Though'],['She studied hard ___ she could pass.',['although','because','so that','unless'],2,'목적 → so that'],['I won\'t go out ___ it stops raining.',['when','after','unless','although'],2,'조건 부정 → unless (= if not)'],['___ finishing his homework, he watched TV.',['After','Before','While','Because'],0,'완료 후 → After finishing (분사구문)'],['___ walking to school, she met her friend.',['Before','After','While','Unless'],2,'동시 동작 → While'],['She left early ___ she was tired.',['although','because','while','unless'],1,'이유 → because'],['___ knowing the answer, she kept quiet.',['Despite','Although','Because','Unless'],0,'Despite + -ing = ~에도 불구하고'],['I\'ll call you ___ I arrive.',['although','when','unless','despite'],1,'시간 → when'],['___ he is rich, he is unhappy.',['Because','Although','So','When'],1,'부자인데 불행 → 양보 Although'],['She went to bed early, ___ tired from work.',['feeling','felt','feel','feels'],0,'분사구문 → feeling tired']],vocab:[['although','비록 ~이지만','Although it rained, we went out.'],['unless','~하지 않으면 (=if not)','I won\'t go unless it stops raining.'],['despite','~에도 불구하고 (+명사/ing)','Despite the rain, we went out.'],['so that','~하기 위하여','She studied hard so that she could pass.'],['while','~하는 동안','While walking, she met a friend.'],['because','~때문에','She left early because she was tired.'],['therefore','그러므로','He was tired. Therefore, he went to bed.'],['however','그러나','It rained. However, we went out.'],['moreover','게다가','He is smart. Moreover, he is kind.'],['furthermore','더욱이','The food was bad. Furthermore, it was expensive.']],writing:[['비가 왔지만, 우리는 산책을 나갔다.','___ it was raining, we went for a walk.',['Although','Though']],['그녀는 시험에 합격하기 위해 열심히 공부했다.','She studied hard ___ she could pass.',['so that']],['비가 그치지 않으면 나는 나가지 않을 것이다.','I won\'t go out ___ it stops raining.',['unless']],['숙제를 끝낸 후에, 그는 TV를 봤다.','___ finishing his homework, he watched TV.',['After']],['그녀는 피곤해서 일찍 잠자리에 들었다.','She went to bed early ___ she was tired.',['because']],['학교에 걷는 동안, 그녀는 친구를 만났다.','___ walking to school, she met a friend.',['While']],['그가 부자이지만, 그는 불행하다.','___ he is rich, he is unhappy.',['Although','Though']],['내가 도착하면 전화할게.','I\'ll call you ___ I arrive.',['when']],['그것을 알면서도, 그녀는 조용히 있었다.','___ knowing the truth, she kept quiet.',['Despite']],['일에 지쳐서, 그녀는 일찍 잠자리에 들었다.','___ tired from work, she went to bed early.',['Feeling']]]},
  {day:20,lesson:'Lesson 96-99',title:'가정법',grammar:[['If I ___ rich, I would travel the world.',['am','was','were','be'],2,'가정법 과거: if + were (be동사)'],['If she had studied harder, she ___ passed.',['will have','would have','would','had'],1,'가정법 과거완료 → would have p.p.'],['I wish I ___ taller.',['am','was','were','be'],2,'wish + 가정법 과거 → were'],['If it ___ tomorrow, we\'ll cancel the picnic.',['rain','rains','rained','would rain'],1,'실현 가능한 조건 → 현재형 rains'],['If I ___ the lottery, I would buy a house.',['win','won','have won','had won'],1,'가정법 과거 → won'],['She talks as if she ___ everything.',['know','knew','has known','knows'],1,'as if + 가정법 과거 → knew'],['I wish I ___ studied harder.',['have','had','was','were'],1,'wish + 가정법 과거완료 → had studied'],['If he ___ harder, he would succeed.',['work','works','worked','had worked'],2,'가정법 과거 → worked'],['If she ___ left earlier, she wouldn\'t have missed the bus.',['has','had','was','were'],1,'가정법 과거완료 → had left'],['Without your help, I ___ failed.',['will have','would have','would','had'],1,'가정법 과거완료 귀결절 → would have']],vocab:[['subjunctive','가정법의','If I were rich, I would travel.'],['condition','조건','What would you do under this condition?'],['wish','바라다, ~했으면 좋겠다','I wish I were taller.'],['lottery','복권','If I won the lottery, I would buy a house.'],['succeed','성공하다','If he worked harder, he would succeed.'],['regret','후회하다','I wish I had studied harder.'],['imaginary','상상의, 가상의','This is an imaginary situation.'],['as if','마치 ~인 것처럼','She talks as if she knew everything.'],['without','~없이','Without your help, I would have failed.'],['otherwise','그렇지 않으면','Study hard. Otherwise, you will fail.']],writing:[['내가 부자라면, 세계 여행을 할 텐데.','If I ___ rich, I would travel the world.',['were']],['내가 더 열심히 공부했더라면, 시험에 합격했을 텐데.','If I had studied harder, I ___ passed.',['would have']],['나는 키가 더 컸으면 좋겠다.','I wish I ___ taller.',['were']],['내일 비가 오면, 우리는 소풍을 취소할 것이다.','If it ___ tomorrow, we\'ll cancel the picnic.',['rains']],['그녀는 모든 것을 아는 것처럼 말한다.','She talks as if she ___ everything.',['knew']],['복권에 당첨된다면, 집을 살 텐데.','If I ___ the lottery, I would buy a house.',['won']],['더 열심히 공부했더라면 좋았을 텐데.','I wish I ___ studied harder.',['had']],['그가 더 열심히 일한다면, 성공할 텐데.','If he ___ harder, he would succeed.',['worked']],['그녀가 더 일찍 떠났더라면, 버스를 놓치지 않았을 텐데.','If she ___ left earlier, she wouldn\'t have missed the bus.',['had']],['당신의 도움이 없었다면, 나는 실패했을 것이다.','Without your help, I ___ failed.',['would have']]]}
];

async function migrate() {
  console.log(`마이그레이션 시작: ${DAYS.length}개 Day`);

  for (const d of DAYS) {
    // Day 생성
    const dayResult = await query(`INSERT INTO days (subject_id, day_number, lesson, title, sort_order) VALUES ('${SUBJECT_ID}', ${d.day}, '${esc(d.lesson)}', '${esc(d.title)}', ${d.day}) RETURNING id`);
    const dayId = dayResult[0].id;
    console.log(`Day ${d.day} 생성: ${dayId}`);

    let order = 0;

    // Grammar → multiple-choice
    for (const q of d.grammar) {
      const data = { question: q[0], options: q[1], correctIndex: q[2], explanation: q[3] };
      await query(`INSERT INTO questions (day_id, template_id, data, sort_order) VALUES ('${dayId}', 'multiple-choice', '${jsonEsc(data)}'::jsonb, ${order++})`);
    }
    console.log(`  grammar ${d.grammar.length}문제`);

    // Writing → fill-in-blank
    for (const q of d.writing) {
      const data = { prompt: q[0], template: q[1], acceptedAnswers: q[2], explanation: '' };
      await query(`INSERT INTO questions (day_id, template_id, data, sort_order) VALUES ('${dayId}', 'fill-in-blank', '${jsonEsc(data)}'::jsonb, ${order++})`);
    }
    console.log(`  writing ${d.writing.length}문제`);

    // Vocab → vocabulary
    for (const q of d.vocab) {
      const data = { word: q[0], meaning: q[1], example: q[2] };
      await query(`INSERT INTO questions (day_id, template_id, data, sort_order) VALUES ('${dayId}', 'vocabulary', '${jsonEsc(data)}'::jsonb, ${order++})`);
    }
    console.log(`  vocab ${d.vocab.length}개`);
  }

  console.log('마이그레이션 완료!');
}

migrate().catch(console.error);
